basePath: /
definitions:
  entities.Account:
    properties:
      id:
        type: integer
      login:
        type: string
      password:
        type: string
      salt:
        type: string
    type: object
  entities.Student:
    properties:
      fio:
        type: string
      groupName:
        type: string
      id:
        type: integer
      phoneNumber:
        type: string
    type: object
  requests.CreateAccountRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  requests.CreateStudentRequest:
    properties:
      fio:
        type: string
      group_name:
        type: string
      phone_number:
        type: string
    type: object
  requests.UpdateStudentRequest:
    properties:
      fio:
        type: string
      group_name:
        type: string
      id:
        type: integer
      phone_number:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Backend for KeenEye
  title: Backend for KeenEye
  version: 1.0.0
paths:
  /api/create-account:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Account credentials
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/requests.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Account'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create account
      tags:
      - account
  /api/create-student:
    post:
      consumes:
      - application/json
      description: Create a new student
      parameters:
      - description: Student info
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/requests.CreateStudentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Student'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      security:
      - BasicAuth: []
      summary: Create student
      tags:
      - students
  /api/delete-student:
    delete:
      description: Delete student by ID
      parameters:
      - description: Student ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      security:
      - BasicAuth: []
      summary: Delete student
      tags:
      - students
  /api/read-all-students:
    get:
      description: Returns list of all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Student'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all students
      tags:
      - students
  /api/read-student:
    get:
      description: Returns a student by ID
      parameters:
      - description: Student ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Student'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get student by ID
      tags:
      - students
  /api/update-student:
    put:
      consumes:
      - application/json
      description: Update student info
      parameters:
      - description: Updated student info
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateStudentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Student'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      security:
      - BasicAuth: []
      summary: Update student
      tags:
      - students
securityDefinitions:
  BasicAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
